services:
  scientifiksApp:
    container_name: scientifiksApp
    build: .
    image: scientifiks:1.0
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - 9500:9500
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - scientifiks_net
    depends_on:
      - scientifiksdb

  scientifiksdb:
    container_name: scientifiksdb
    image: mariadb:latest
    deploy:
      resources:
        limits:
          memory: 256M
    env_file: .env
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - scientifiks_net
    restart: unless-stopped

networks:
  scientifiks_net:
    name: scientifiks_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.35.0.0/24
