services:
  scientifiksApp:
    container_name: scientifiksApp
    build: .
    image: scientifiks:1.0
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - 9500:9500
    volumes:
      - ./app:/app #carpeta puente entre el contenedor y la maquina fisica.
    restart: unless-stopped #politica de reinicio, solo se detendra cuando el administrador la detenga
    networks:
      - scientifiks_net
    environment:
      - TZ=America/Panama


networks:
  scientifiks_net:  
    name: scientifiks_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.35.0.0/24 #red interna del contenedor
